### PR TITLE
Update version of chefspec used

### PR DESCRIPTION
**Pull request by jtslear**

### CODE REVIEW

**Comment by derekschultz** [comment]
Concerns:
* Deprecate ChefSpec::Runner.new - you should specify if you want a SoloRunner or ServerRunner
* Deprecate ChefSpec::Runner.define_runner_method in favor of ChefSpec.define_matcher

These are the two major changes that would require us to refactor our cookbook tests.

**Comment by jtslear** [comment]
Excellent points @derekschultz.  Note that the first item you mention, in the latest version of chefspec he does provide a deprecation class, such that Runner.new will default to SoloRunner.new: https://github.com/sethvargo/chefspec/blob/dfb89e09e3a2685d036b389dff35a7624b4f6c77/lib/chefspec/deprecations.rb#L31

**Comment by jtslear** [comment]
@derekschultz looks like your second item was addressed as well:
https://github.com/sethvargo/chefspec/blob/dfb89e09e3a2685d036b389dff35a7624b4f6c77/lib/chefspec/deprecations.rb#L26

**Comment by derekschultz** [comment]
@jtslear -- Interesting, thanks for pointing that out. I'd like to test this first: update the version in the gemspec locally, then test a cookbook by updating the Gemfile to be:

```
source 'https://rubygems.org'
#gem 'cookbook-development', :git => 'https://github.com/RallySoftware-cookbooks/cookbook-development'
gem 'cookbook-development', :path => '../cookbook-development
```

**Comment by derekschultz** [comment]
Then I'll be :+1:

**Comment by cbechberger** [comment]
The only thing I ask is that according to semver the major version number should be bumped...

**Pull request merged**
